[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "darshan-trace-parser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "darshan>=3.4.7.0",
    "ipykernel>=6.29.5",
    "notebook>=7.4.3",
    "pip==25.1",
]

[tool.setuptools]
package-dir = {"" = "src"}
